### ISSUE TITLE
Important question

### ISSUE THREAD

**Issue by ghost** [octalmage/gatsby-plugin-sentry#19] opened 2019-04-14 18:17 UTC
Hello dear Developer!

Where should this code be inserted? /src/utils/sentry.js or where?
Thank you!

```export default class ErrorBoundary extends React.Component {
  
  constructor(props) {
    super(props);
    this.state = { error: null };
  }

  componentDidCatch(error, errorInfo) {
    this.setState({ error });
    Sentry.configureScope((scope) => {
      Object.keys(errorInfo).forEach(key => {
        scope.setExtra(key, errorInfo[key]);
      });
    });
    Sentry.captureException(error);
  }

  render() {
    if (this.state.error) {
      // render fallback UI
      return <h1>Something went wrong!</h1>;
    } else {
      // when there's not an error, render children untouched
      return this.props.children;
    }
  }
}

**Comment by thomascorthouts** [comment] 2019-04-22 13:44
This should be your wrapper element, this can be done in a couple of different ways, one would be to wrap every page with `<Sentry>...</Sentry>` and put it as you said in `src/utils/sentry.js`

A nicer approach I personally prefer, as this is some higher level wrapper, is to include the component in your `gatsby-browser.js` and `gatsby-ssr.js` as `exports.wrapRootElement = SentryWrapper`, the advantage is that it's going to wrap it around all pages you render.

This is just one approach though, I hope to learn from others with different approaches...

**Comment by zanfirovidius** [comment] 2019-05-27 13:27
Hi @thomascorthouts  

Can you offer an example? I am trying to implement the same approach but every time I am getting this error saying : "Module not found".

I am using Typescript. Can this be the reason?

Thank you.

**Comment by thomascorthouts** [comment] 2019-05-27 13:36
Hey @zanfirovidius 

I'm happy to help! Because of the moment this plugin is used, when you use the wrapRootElement, it might be the case that there is a typescript issue, but it's also just a struggle to get it right. How far did you get so far? Is there maybe a repo I can check with your current progress?

**Comment by zanfirovidius** [comment] 2019-05-27 13:53
Hi.

So right now the plugin send errors to sentry using the plugin (Except that i can make sens of how to define the enviroments on Sentry).

The problem is with the second part.

I have a component called sentryWrapper.tsx that looks like this:

import * as Sentry from '@sentry/browser';
import React from 'react';

interface IState {
  error: object | null;
}

export class SentryWrapper extends React.Component<{ children: React.ReactNode }, IState> {
  state: IState = { error: null };

  componentDidCatch(error: any, errorInfo: any) {
    this.setState({ error });
    Sentry.configureScope(scope => {
      Object.keys(errorInfo).forEach(key => {
        scope.setExtra(key, errorInfo[key]);
      });
    });
    Sentry.captureException(error);
  }

  render() {
    if (this.state.error) {
      return ---error message---;
    } else {
      return this.props.children;
    }
  }
}


and it is used in gatsb-ssr.js and gatsby-browser.js like this:

import React from 'react';
import { SentryWrapper } from 'src/util/sentryWrapper';

export const wrapPageElement = ({ element }) => {
  return <SentryWrapper className="test">{element}</SentryWrapper>;
};

**Comment by zanfirovidius** [comment] 2019-05-27 13:53
Sorry for the formatting of the message :)

**Comment by zanfirovidius** [comment] 2019-05-27 13:55
sorry. my mistake is not sending either the error message to sentry.

**Comment by thomascorthouts** [comment] 2019-05-27 13:58
Could you try to change the part in the `gatsby-ssr.js` and `gatsby-browser.js` to the line beneath? 
```
exports.wrapRootElement = SentryWrapper;
```

**Comment by zanfirovidius** [comment] 2019-05-27 14:01
import { SentryWrapper } from 'src/util/sentryWrapper';
exports.wrapRootElement = SentryWrapper;


like this it will give the fallowing error:
This plugin file is using both CommonJS and ES6 module systems together which we don't support.
You'll need to edit the file to use just one or the other.

**Comment by thomascorthouts** [comment] 2019-05-27 14:03
Oh, my bad, if you want to use the version you're using, it should probably become something like this:

```
export const wrapRootElement = ({ element }) => {
return <SentryWrapper>{element}</SentryWrapper>;
};
```

Because now it seems, that in those 2 files, you don't really use the SentryWrapper, you just import it.

**Comment by zanfirovidius** [comment] 2019-05-27 14:08
I added this but it seams that is not doing anything....


/*eslint-disable */
import React from 'react';
export const wrapRootElement = ({ element }) => {
  return <SentryWrapper className="test">{element}</SentryWrapper>;
};
/*eslint-enable */

**Comment by thomascorthouts** [comment] 2019-05-27 14:10
yes, because you just return element, but could you give it a try to put this: 
```
return <SentryWrapper>{element}</SentryWrapper>;
``` 
instead of 
```
return {element};
```

**Comment by zanfirovidius** [comment] 2019-05-27 14:11
Sorry... having problem with the mark editor :) I did added like that:

`/*eslint-disable */
import React from 'react';
export const wrapRootElement = ({ element }) => {
  return <SentryWrapper className="test">{element}</SentryWrapper>;
};
/*eslint-enable */`

**Comment by thomascorthouts** [comment] 2019-05-27 14:13
No worries, it's not that easy at all times, just one follow-up idea I have, could you try to do it like this?
```
/*eslint-disable */ 
import React from 'react';
import { SentryWrapper } from 'src/util/sentryWrapper';
export const wrapRootElement = ({ element }) => { 
return <SentryWrapper className="test">{element}</SentryWrapper>; 
}; 
/*eslint-enable */
```

**Comment by zanfirovidius** [comment] 2019-05-27 14:15
<img width="1176" alt="Screenshot 2019-05-27 at 17 14 32" src="https://user-images.githubusercontent.com/11194709/58425614-e665cf80-80a2-11e9-9c2a-59e18d62d242.png">

**Comment by thomascorthouts** [comment] 2019-05-27 14:17
Oh, yeah, that's a resolving issue, babel and webpack aren't processing the paths for files at that point, that could be fixed by changing this line
`import { SentryWrapper } from 'src/util/sentryWrapper';`
to
`import { SentryWrapper } from './src/util/sentryWrapper';`

**Comment by zanfirovidius** [comment] 2019-05-27 14:29
It works ... in a way.... it renders the component but it dose not trigger the componentDidCatch. I will keep looking in to this tomorrow.

Thank you for the help. :)

**Closed as completed** 2024-01-28 17:57 UTC
